# Spring Cloud Config — opcional para entorno local
spring.config.import=optional:configserver:

# =============================================
# GestoPago - Autenticación
# =============================================
gestopago.auth.url=https://api.gestopago.com
gestopago.auth.id-distribuidor=0
gestopago.auth.codigo-dispositivo=CODIGO
gestopago.auth.password=182201  
gestopago.auth.refresh-rate-ms=3600000

# =============================================
# GestoPago - Servicio de Productos
# =============================================
gestopago.productos.url=https://integ-api-mobile.gestopago.com
gestopago.productos.token=50847b48378019a735e31c9a967d22118f07b83ed0c95af5d9cf53518fc059a8
# =============================================
# PostgreSQL — Base de datos principal
# =============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/gestopago_db
spring.datasource.username=postgres
spring.datasource.password=Admin123

# Flyway
spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=public

# =============================================
# MongoDB — Cat Product
# =============================================
spring.data.mongodb.uri=mongodb://localhost:27017/gestopago_db
spring.data.mongodb.database=gestopago_db


